server:
  port: 80


eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#ribbon:
#  ReadTimeout:  5000
#  ConnectTimeout: 5000

spring:
  application:
    name: cloud-provider-hystrix-order

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。